# idempiere install
image:
  file: .gitpod.Dockerfile

# exposed ports
ports:
- port: 5432 # PostgreSQL
  onOpen: ignore
# - port: 8080 # Web
#   onOpen: ignore
# - port: 8443 # SSL
#   onOpen: ignore

# Start up tasks:
tasks:
  # Will be executed one time when creating a workspace, command: will be excuted each time you open workspace
  - init: |
      sudo sed 's/peer/md5/g' /etc/postgresql/12/main/pg_hba.conf
      psql -U gitpod -c "CREATE ROLE adempiere SUPERUSER LOGIN PASSWORD 'adempiere'"
      createdb --template=template0 -E UNICODE -O adempiere -U adempiere idempiere
      psql -d idempiere -U adempiere -c "ALTER ROLE adempiere SET search_path TO adempiere, pg_catalog"
      psql -d idempiere -U adempiere -c 'CREATE EXTENSION "uuid-ossp"'
      sleep 1
      pg_ctl restart
    command: |
      sleep 1
      ./setup.sh --depth=1 --branch=release-8.2 --skip-setup-db=true --skip-migration-script=true

# If you want to use migration script and db script to auto setup idempiere database you may use this line instead of the one above:
# ./setup.sh --depth=1 --branch=release-8.2 --db-name=idempiere --db-user=adempiere --db-pass=adempiere --db-pg-name=postgres --db-pg-user=gitpod
# P.S We'll skip those scripts for now, as they aren't stable enough!

  - command: pg_ctl status
