# idempiere install
image:
  file: .gitpod.Dockerfile

# exposed ports
ports:
- port: 5432 # PostgreSQL
  onOpen: ignore
# - port: 8080 # Web
#   onOpen: ignore
# - port: 8443 # SSL
#   onOpen: ignore

# Start up tasks:
tasks:
  # Will be executed one time when creating a workspace, command: will be excuted each time you open workspace
  - init: |
      psql -U gitpod -c "CREATE ROLE adempiere SUPERUSER LOGIN PASSWORD 'adempiere'"
      createdb --template=template0 -E UNICODE -O adempiere -U adempiere idempiere
      psql -d idempiere -U adempiere -c "ALTER ROLE adempiere SET search_path TO adempiere, pg_catalog"
      psql -d idempiere -U adempiere -c 'CREATE EXTENSION "uuid-ossp"'
      pg_ctl restart
      sdk selfupdate -y
      sdk install groovy 3.0.7
    command: |
      chmod +x setup.sh
      ./setup.sh --depth=1 --branch=release-8.2
      cd idempiere
      mvn verify -U
      export IDEMPIERE_REPOSITORY=$(pwd)
      echo $IDEMPIERE_REPOSITORY
      cd /tmp
      jar xvf $IDEMPIERE_REPOSITORY/org.adempiere.server-feature/data/seed/Adempiere_pg.jar
      psql -d idempiere -U adempiere -f Adempiere_pg.dmp
      cd $IDEMPIERE_REPOSITORY/org.idempiere.p2/target/products/org.adempiere.server.product/linux/gtk/x86_64
      chmod +x console-setup.sh
      ./console-setup.sh
# P.S. Here we use "gitpod" instead of the default "postgres" user

  - command: pg_ctl status
