# idempiere install
image:
  file: .gitpod.Dockerfile

# exposed ports
ports:
- port: 5432
  onOpen: ignore
# - port: 8080
#   onOpen: ignore

# start up tasks: Will be executed one time when creating a workspace, command: will be exected each time you open workspace
tasks:
  # Here we use "gitpod" instead of the default "postgres" user
  - init: |
      psql -U gitpod -c "CREATE ROLE adempiere SUPERUSER LOGIN PASSWORD 'adempiere'"
      createdb --template=template0 -E UNICODE -O adempiere -U adempiere idempiere
      psql -d idempiere -U adempiere -c "ALTER ROLE adempiere SET search_path TO adempiere, pg_catalog"
      psql -d idempiere -U adempiere -c 'CREATE EXTENSION "uuid-ossp"'
      pg_ctl restart
    command: |
      chmod +x ./setup.sh
      ./setup.sh --depth=1 --branch=release-8.2
      cd idempiere
      mvn verify -U

  - command: pg_ctl status
